services:

  db:
    image: postgres:12.16-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: postgres_container
    restart: unless-stopped
    command: >
      sh -c "
      if [ -z \"$(ls -A /var/lib/postgresql/data)\" ]; then
        initdb -D /var/lib/postgresql/data/pgdata
      fi &&
      exec docker-entrypoint.sh postgres
      "